08-generic-view/route/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# To make {% url 'route:first-view' %} work in templates
# Also, add namespace in project urls.py 
# Otherwise the name='' values will be global across all applications
app_name = 'route'  

urlpatterns = [
    path('', TemplateView.as_view(template_name='route/main.html')),
    path('first', views.FirstView.as_view(), name='first-view'),
    path('second', views.SecondView.as_view(), name='second-view'),
]

# References

# https://docs.djangoproject.com/en/4.2/topics/http/urls/

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

# https://docs.djangoproject.com/en/4.2/topics/http/urls/#url-namespaces-and-included-urlconfs

08-generic-view/route/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import View

class FirstView(View):  
    def get(self, request) :
        return render(request, 'route/main.html')

class SecondView(View):  
    def get(self, request) :
        u = reverse('gview:cats')
        u2 = reverse('gview:dogs')
        u3 = reverse('gview:dog', args=['42'] )
        ctx = {'x1' : u, 'x2': u2, 'x3': u3 }
        return render(request, 'route/second.html', ctx)

# References

# https://docs.djangoproject.com/en/4.2/topics/http/urls/#topics-http-reversing-url-namespaces

08-generic-view/route/templates/route/main.html
<h1>Using the url tag</h2>
<ul>
    <li>
        <a href="/route/second-view">
        hard-coded</a> (not DRY)
    </li>
    <li>
        {% url 'route:first-view' %}
        (url 'route:first-view')
    </li>
    <li>
        <a href="{% url 'route:second-view' %}">
        url 'route:second-view'</a>
    </li>
    <li>
        {% url 'gview:cats' %}
        (url 'gview:cats') from gview/urls.py
    </li>
    <li>
        {% url 'gview:cat' 42 %}
        (url 'gview:cat' 42) from gview/urls.py
    </li>
    <li>
        {% url 'nsroute:second-view' %}
        (url 'nsroute:second-view') from dj4e-samples/urls.py
    </li>
</ul>
<p>
<a href="https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#url" target="_blank">Documentation</a>
</p>

08-generic-view/route/templates/route/second.html
<h1>Reverse URLs</h2>
<ul>
    <li>
        <a href="{% url 'route:first-view' %}">
        route:first-view</a>
    </li>
    <li>
        {{ x1 }} (x1 from context)
    </li>
    <li>
        {{ x2 }} (x2 from context)
    </li>
    <li>
        {{ x3 }} (x3 from context)
    </li>
</ul>
<p>
<a href="https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#url" target="_blank">Documentation</a>
</p>